spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/study
    password: ''
  application:
    name: frameWorkStudy
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000ms
  jwt:
    secret: 7Yag7YGwIOu5hOuwgO2CpCDthYzsiqTtirgg7J6F64uI64ukIO2FjOyKpO2KuCA=
logging:
  level:
    root: debug