spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/study
    password: ''
  application:
    name: frameWorkStudy
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000ms
logging:
  level:
    root: debug
jwt:
  secret: tmvmfldvmfpdladnjzmwpdlejqmfdbxltlzmfltzldlqslekalks
