### 게시글 작성 API
# @no-redirect
POST http://localhost:8080/api/board
Content-Type: application/json

{
  "title" : "2게시글 제목 테스트입니다.",
  "contents" : "2게시글 내용 테스트 입니다.",
  "author" : "작성자2"
}

### 게시글 리스트 조회 API
GET http://localhost:8080/api/boards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXIzIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3MzM2NDE2NTYsImV4cCI6MTczMzY0MTY5Mn0.BBS-9HGVVDkBV4P_5lW4OvnOBje7x5Yj-6DnFLy8Wvw
Content-Type: application/json


### 게시글 상세 조회 API
GET http://localhost:8080/api/board/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXIzIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3MzM2NDE3MTUsImV4cCI6MTczMzY0MTc1MX0.4MwhGGElAHTLOVa-ZuzGFTg8BZ3b9567pZ62EzphQRs
Content-Type: application/json

### 게시글 수정 API
PUT http://localhost:8080/api/board/1
Content-Type: application/json

{
  "title" : "수정된 제목2",
  "contents" : "수정된 내용2",
  "author" : "작성자3"
}

### 게시글 삭제 API
DELETE http://localhost:8080/api/board/2
Content-Type: application/json