### 회원가입 API
POST http://localhost:8080/api/user
Content-Type: application/json

{
"userId" : "user3",
"name" : "홍준영",
"password" : "test123!@#"
}

### 로그인 API
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=user3&password=test123!@#